-- Local SQLite fallback schema (CLAUDE.md §18: "Label as local prototype
-- fallback"). Two groups of tables:
--
-- 1. Business-data mirror (COMPANIES, RISK_ALERTS, TRANSACTIONS, ...) —
--    shaped exactly like the cleaned TEAM_11_USER snapshot documented in
--    docs/data-quality-report.md, populated by scripts/seed_local_demo.py
--    with a small, clearly-synthetic demo set. Only exists so the app is
--    runnable end-to-end without the tenant credentials file.
-- 2. App-state tables (CASES, NARRATIVE_DRAFTS, DECISIONS,
--    WORKFLOW_INSTANCES, AUDIT_EVENTS, ...) — the real interface contract,
--    identical in shape to migrations/001_app_schema.sql (HANA). This half
--    is not a "fallback" in the disclosure sense; it's the same schema on a
--    different engine.

PRAGMA foreign_keys = ON;

-- ---------- business-data mirror ----------

CREATE TABLE IF NOT EXISTS COMPANIES (
    COMPANY_ID TEXT PRIMARY KEY,
    LEGAL_NAME TEXT,
    REGISTRATION_NUMBER TEXT,
    LEI_CODE TEXT,
    INCORPORATION_COUNTRY_ID TEXT,
    HEADQUARTERS_COUNTRY_ID TEXT,
    INDUSTRY_ID TEXT,
    KYC_STATUS TEXT,
    KYC_RISK_RATING TEXT,
    KYC_VERIFIED_DATE TEXT,
    KYC_EXPIRY_DATE TEXT,
    KYC_EFFECTIVE_STATUS TEXT,
    KYC_DQ_FLAG TEXT,
    ANNUAL_REVENUE_USD REAL,
    EMPLOYEE_COUNT INTEGER,
    CLIENT_SEGMENT TEXT,
    RESTRICTED_FLAG INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS COUNTRIES (
    COUNTRY_ID TEXT PRIMARY KEY,
    COUNTRY_NAME TEXT,
    RISK_RATING TEXT
);

CREATE TABLE IF NOT EXISTS COMPANY_RISK_PROFILES (
    COMPANY_ID TEXT PRIMARY KEY REFERENCES COMPANIES(COMPANY_ID),
    COMPOSITE_RISK_SCORE REAL,
    COUNTRY_RISK_SCORE REAL,
    RISK_TIER TEXT
);

CREATE TABLE IF NOT EXISTS COMPANY_BENEFICIAL_OWNERS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    COMPANY_ID TEXT REFERENCES COMPANIES(COMPANY_ID),
    OWNER_NAME TEXT,
    OWNERSHIP_PERCENTAGE REAL,
    OWNERSHIP_DQ_FLAG TEXT,
    COMPANY_OWNERSHIP_SUM REAL,
    PEP_FLAG INTEGER DEFAULT 0,
    SANCTIONS_REFERENCE_FLAG INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    TRANSACTION_ID TEXT PRIMARY KEY,
    TRANSACTION_UUID TEXT,
    TRANSACTION_REF TEXT,
    ORIGINATOR_COMPANY_ID TEXT REFERENCES COMPANIES(COMPANY_ID),
    BENEFICIARY_COMPANY_ID TEXT REFERENCES COMPANIES(COMPANY_ID),
    BENEFICIARY_NAME TEXT,
    AMOUNT_ORIGINAL REAL,
    AMOUNT_USD REAL,
    CURRENCY_ORIGINAL TEXT,
    INITIATED_AT TEXT,
    SETTLED_AT TEXT,
    VALUE_DATE TEXT,
    STATUS TEXT,
    ORIGINATING_COUNTRY_ID TEXT,
    DESTINATION_COUNTRY_ID TEXT,
    BENEFICIARY_COUNTRY_ID TEXT,
    EXCHANGE_RATE REAL,
    TRANSACTION_TYPE TEXT,
    PAYMENT_PURPOSE TEXT,
    IS_CROSS_BORDER INTEGER
);

CREATE TABLE IF NOT EXISTS TRANSACTION_BASELINES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    COMPANY_ID TEXT REFERENCES COMPANIES(COMPANY_ID),
    BASELINE_PERIOD TEXT,
    PERIOD_START TEXT,
    PERIOD_END TEXT,
    TOTAL_AMOUNT_USD REAL,
    AVG_AMOUNT_USD REAL,
    MIN_AMOUNT_USD REAL,
    MAX_AMOUNT_USD REAL
);

CREATE TABLE IF NOT EXISTS RISK_ALERTS (
    ALERT_ID TEXT PRIMARY KEY,
    COMPANY_ID TEXT REFERENCES COMPANIES(COMPANY_ID),
    TRANSACTION_ID TEXT REFERENCES TRANSACTIONS(TRANSACTION_ID),
    ALERT_TYPE TEXT,
    ALERT_PRIORITY TEXT,
    STATUS TEXT,
    CREATED_AT TEXT,
    SLA_DUE_AT TEXT,
    RESOLVED_AT TEXT,
    SLA_BREACHED_SOURCE INTEGER,
    SLA_BREACHED_DERIVED INTEGER,
    RESOLUTION_HOURS REAL,
    ALERT_DQ_FLAG TEXT
);

CREATE TABLE IF NOT EXISTS COMPLIANCE_CASES (
    CASE_ID TEXT PRIMARY KEY,
    COMPANY_ID TEXT REFERENCES COMPANIES(COMPANY_ID),
    OPENED_AT TEXT,
    CLOSED_AT TEXT,
    STATUS TEXT,
    SAR_FILED INTEGER,
    SAR_REFERENCE TEXT
);

CREATE TABLE IF NOT EXISTS CASE_ALERTS (
    CASE_ID TEXT REFERENCES COMPLIANCE_CASES(CASE_ID),
    ALERT_ID TEXT REFERENCES RISK_ALERTS(ALERT_ID),
    PRIMARY KEY (CASE_ID, ALERT_ID)
);

CREATE TABLE IF NOT EXISTS SANCTIONS_LISTS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ENTITY_NAME TEXT,
    LIST_NAME TEXT,
    COMPANY_ID TEXT REFERENCES COMPANIES(COMPANY_ID)
);

CREATE TABLE IF NOT EXISTS POLICY_PASSAGES (
    DOCUMENT_ID TEXT,
    PASSAGE_LOCATOR TEXT,
    TEXT TEXT,
    DOC_TYPE TEXT,
    REGION TEXT,
    EFFECTIVE_DATE TEXT,
    PRIMARY KEY (DOCUMENT_ID, PASSAGE_LOCATOR)
);

-- ---------- app-state tables (mirrors migrations/001_app_schema.sql) ----------

CREATE TABLE IF NOT EXISTS CASES (
    CASE_ID TEXT PRIMARY KEY,
    ALERT_ID TEXT NOT NULL REFERENCES RISK_ALERTS(ALERT_ID),
    ASSIGNED_TEAM TEXT,
    STATUS TEXT NOT NULL DEFAULT 'OPEN',
    CREATED_AT TEXT NOT NULL,
    UPDATED_AT TEXT NOT NULL,
    REGION TEXT NOT NULL,
    UNIQUE (ALERT_ID)
);

CREATE TABLE IF NOT EXISTS PRIORITY_SCORES (
    ALERT_ID TEXT NOT NULL REFERENCES RISK_ALERTS(ALERT_ID),
    URGENCY_SCORE REAL NOT NULL,
    URGENCY_TIER TEXT NOT NULL,
    HARD_OVERRIDE_CODE TEXT,
    COMPLEXITY_BAND TEXT NOT NULL,
    COMPLEXITY_POINTS INTEGER NOT NULL,
    POLICY_VERSION TEXT NOT NULL,
    CALCULATED_AT TEXT NOT NULL,
    CAVEATS_JSON TEXT
);

CREATE TABLE IF NOT EXISTS ALERT_FACTORS (
    ALERT_ID TEXT NOT NULL REFERENCES RISK_ALERTS(ALERT_ID),
    FACTOR_CODE TEXT NOT NULL,
    RAW_VALUE TEXT,
    NORMALISED_VALUE REAL NOT NULL,
    WEIGHT REAL NOT NULL,
    WEIGHTED_POINTS REAL NOT NULL,
    REASON_CODE TEXT NOT NULL,
    POLICY_VERSION TEXT NOT NULL,
    CALCULATED_AT TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS PREDICTIVE_SCORES (
    ALERT_ID TEXT NOT NULL REFERENCES RISK_ALERTS(ALERT_ID),
    PREDICTION_TYPE TEXT NOT NULL,
    PREDICTION_VALUE REAL NOT NULL,
    MODEL_NAME TEXT NOT NULL,
    MODEL_VERSION TEXT NOT NULL,
    FEATURE_SNAPSHOT_ID TEXT NOT NULL,
    ADVISORY_ONLY INTEGER NOT NULL DEFAULT 1,
    SCORED_AT TEXT NOT NULL,
    EXTRA_JSON TEXT
);

CREATE TABLE IF NOT EXISTS CASE_FILES (
    CASE_FILE_ID TEXT PRIMARY KEY,
    CASE_ID TEXT NOT NULL REFERENCES CASES(CASE_ID),
    SCHEMA_VERSION TEXT NOT NULL,
    CONTENT_JSON TEXT NOT NULL,
    ASSEMBLED_AT TEXT NOT NULL,
    SOURCE_COVERAGE REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS SOURCE_CITATIONS (
    CITATION_ID TEXT PRIMARY KEY,
    CASE_FILE_ID TEXT NOT NULL REFERENCES CASE_FILES(CASE_FILE_ID),
    SOURCE_TYPE TEXT NOT NULL,
    SOURCE_ID TEXT NOT NULL,
    SOURCE_LOCATOR TEXT NOT NULL,
    SOURCE_VERSION TEXT,
    RETRIEVED_AT TEXT NOT NULL,
    REGION TEXT NOT NULL,
    PERMISSION_SCOPE TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS NARRATIVE_DRAFTS (
    DRAFT_ID TEXT PRIMARY KEY,
    CASE_ID TEXT NOT NULL REFERENCES CASES(CASE_ID),
    DRAFT_VERSION INTEGER NOT NULL,
    CONTENT TEXT NOT NULL,
    GENERATION_ID TEXT,
    PROMPT_VERSION TEXT,
    MODEL_VERSION TEXT,
    CREATED_BY_TYPE TEXT NOT NULL,
    CREATED_AT TEXT NOT NULL,
    VERIFICATION_STATUS TEXT NOT NULL DEFAULT 'unverified'
);

CREATE TABLE IF NOT EXISTS DECISIONS (
    DECISION_ID TEXT PRIMARY KEY,
    CASE_ID TEXT NOT NULL REFERENCES CASES(CASE_ID),
    DECISION_TYPE TEXT NOT NULL,
    RATIONALE TEXT NOT NULL,
    DECIDED_BY TEXT NOT NULL,
    ATTESTED INTEGER NOT NULL,
    DECIDED_AT TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS WORKFLOW_INSTANCES (
    WORKFLOW_ID TEXT PRIMARY KEY,
    CASE_ID TEXT NOT NULL REFERENCES CASES(CASE_ID),
    EXTERNAL_INSTANCE_ID TEXT,
    STATUS TEXT NOT NULL,
    STARTED_AT TEXT NOT NULL,
    COMPLETED_AT TEXT,
    IS_FALLBACK INTEGER NOT NULL DEFAULT 1
);

-- Append-only: application code must never UPDATE/DELETE existing rows here.
CREATE TABLE IF NOT EXISTS AUDIT_EVENTS (
    EVENT_ID TEXT PRIMARY KEY,
    CASE_ID TEXT NOT NULL,
    EVENT_TYPE TEXT NOT NULL,
    ACTOR_TYPE TEXT NOT NULL,
    ACTOR_ID TEXT NOT NULL,
    OBJECT_TYPE TEXT NOT NULL,
    OBJECT_ID TEXT NOT NULL,
    DETAILS_JSON TEXT NOT NULL,
    OCCURRED_AT TEXT NOT NULL,
    CORRELATION_ID TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS IDEMPOTENCY_KEYS (
    IDEMPOTENCY_KEY TEXT NOT NULL,
    ENDPOINT TEXT NOT NULL,
    REQUEST_HASH TEXT NOT NULL,
    RESPONSE_JSON TEXT NOT NULL,
    CREATED_AT TEXT NOT NULL,
    PRIMARY KEY (IDEMPOTENCY_KEY, ENDPOINT)
);

CREATE TABLE IF NOT EXISTS DQ_ISSUES (
    ISSUE_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    OBJECT_NAME TEXT NOT NULL,
    ISSUE_CODE TEXT NOT NULL,
    DESCRIPTION TEXT NOT NULL,
    AFFECTED_ROWS INTEGER NOT NULL,
    ACTION_TAKEN TEXT NOT NULL,
    DETECTED_AT TEXT NOT NULL
);
